# Week4授業前課題3 オブジェクト指向の活用<br>

#### オブジェクト指向について

これまでの課題では触れてきませんでしたが、`StandardScaler`や`LinearRegression`のような**クラス**と呼ばれるものがPythonなどのプログラム言語では利用できます。<br>
<br>
クラスの構文は、オブジェクト指向と呼ばれる考え方を利用したプログラミングの基本的な道具になります。<br>
<br>
この課題ではこれまでに既に登場していたクラスを例に、クラスを活用することでどのようなことができるのかを見て学んでいきます。そして課題の後半では`StandardScaler`のクラスをスクラッチで自作します。

## 【問題1】これまで利用してきたクラスの列挙
クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。<br>
<br>
Pandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。

>- Pandas: DataFrame、Series等
>- matplotlib: Patch、Circle等
>- scikit-learn: LinearRegression、SVR、RandomForestClassifier等

## 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙
これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。<br>
<br>
最低でもそれぞれ5つ以上答えてください。<br>

<br>

**《ndarrayやstrもインスタンス》**<br>
<br>
ドットをつけるというと、NumPyのndarrayに対してndarray.shapeやndarray.sum()のような使い方は何度も利用してきたかと思います。これは、ndarrayもインスタンスオブジェクトであり、shapeはインスタンス変数、sumはメソッドだったということです。<br>
<br>
Pythonのコードに登場するデータはどれもインスタンスオブジェクトであり、listやstrもメソッドを持ちます。

>- インスタンス：bool, dict, tuple, decimal, int, dataframe
>- メソッド：reshape, concatenate, append, format, loc

## 【問題3】標準化クラスをスクラッチで作成
理解をより深めるため、`StandardScaler`をスクラッチで作成しましょう。scikit-learnは使わず、NumPyなどを活用して標準化の計算を記述します。具体的には`fit`メソッドと`transform`メソッドを作ります。<br>
<br>
今回は雛形を用意しました。クラスの作成方法は関数に近いです。メソッドはクラスの中にさらにインデントを一段下げて記述します。<br>
<br>
インスタンス変数を作成する際は`self.mean_`のように`self`を付けます。クラスの外から`scaler.mean_`と書いていたscalerの部分が自分自身を表すselfになっています。

In [10]:
class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = np.mean(X)
        self.var_ = np.var(X)
        
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        
        X_scaled = X - self.mean_    # 各要素から平均値を引く

        X_scaled = X / self.var_     # 各要素を偏差で割る

        return X_scaled

In [5]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : 2.46
分散 : 3.1744
[[1.60660282 1.10257056 0.44102823 0.06300403]
 [1.54359879 0.94506048 0.44102823 0.06300403]
 [1.48059476 1.00806452 0.40952621 0.06300403]
 [1.44909274 0.9765625  0.47253024 0.06300403]
 [1.57510081 1.13407258 0.44102823 0.06300403]
 [1.70110887 1.22857863 0.53553427 0.12600806]
 [1.44909274 1.07106855 0.44102823 0.09450605]
 [1.57510081 1.07106855 0.47253024 0.06300403]
 [1.38608871 0.91355847 0.44102823 0.06300403]
 [1.54359879 0.9765625  0.47253024 0.03150202]]


## 【問題4】 四則演算を行うクラスの作成
コンストラクタの動作を確認するためのサンプルコードを用意しました。コンストラクタは、インスタンス化が行われる時に自動的に実行されるという働きがあります。こういった特殊な動作をするメソッドを、**特殊メソッド**と呼びます。<br>

<br>

**《サンプルコード》**

```
class ExampleClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
```

上記ExampleClassは足し算のメソッドを持っていますが、これに引き算、掛け算、割り算のメソッドを加えてください。<br>
<br>
コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出すようにしてください。<br>
<br>
クラス名や説明文も適切に書き換えてください。

In [38]:
class SimpleCalculator():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        if isinstance(value, (int, float)):
            self.value = value
        else:
            raise TypeError("Value must be a number!")
            
        print("初期値{}が設定されました".format(self.value))
        
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        try:
            self.value += value2
        except TypeError as e:
            print("TypeError:", e)
    def sub(self, value3):
        """
        受け取った引数をself.valueから引く
        """
        try:
            self.value -= value3
        except TypeError as e:
            print("TypeError:", e)
    def mul(self, value4):
        """
        受け取った引数をself.valueに掛ける
        """
        try:
            self.value *= value4
        except TypeError as e:
            print("TypeError:", e)
    def div(self, value5):
        """
        受け取った引数をself.valueから割る
        """
        try:
            self.value /= value5
        except TypeError as e:
            print("TypeError:", e)

In [39]:
example = SimpleCalculator(1)

example.add(3)
print("Add 3 : {}".format(example.value))

example.sub(3)
print("Subtract 3 : {}".format(example.value))

example.mul(3)
print("Multiply by 3 : {}".format(example.value))

example.div(3)
print("Divide by 3 : {}".format(example.value))

初期値1が設定されました
Add 3 : 4
Subtract 3 : 1
Multiply by 3 : 3
Divide by 3 : 1.0


In [40]:
# 例外処理の発生
exception = SimpleCalculator('hi')

TypeError: Value must be a number!